name: pandoo
display_name: "Pandoo"
description: "A simple todo list app"

publish_to: 'none'
version: 2.5.0+14
license: PolyForm-Noncommercial-1.0.0
repository: https://github.com/teamsuperpanda/pandoo
issue_tracker: https://github.com/teamsuperpanda/pandoo/issues

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.3
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  awesome_snackbar_content: ^0.1.8
  flutter_native_splash: ^2.4.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0
  mockito: ^5.4.4
  flutter_launcher_icons: ^0.14.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/icon/icon.png
    - assets/fonts/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#1E1E1E"
  image: assets/images/launchscreen/logo_light.png
  image_dark: assets/images/launchscreen/logo_dark.png
  branding: assets/images/launchscreen/branding_light.png
  branding_dark: assets/images/launchscreen/branding_dark.png

  android_12: 
    image: assets/images/launchscreen/logo_light.png
    image_dark: assets/images/launchscreen/logo_dark.png
    branding: assets/images/launchscreen/branding_light.png
    branding_dark: assets/images/launchscreen/branding_dark.png
    color: "#FFFFFF"
    color_dark: "#1E1E1E"
  android: true
  ios: true
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/icon/icon.png"
