name: pandoo
description: "A simple todo list app"

publish_to: 'none'
version: 2.3.0+12

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  awesome_snackbar_content: ^0.1.8
  flutter_native_splash: ^2.4.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  mockito: ^5.4.4
  flutter_launcher_icons: ^0.14.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/icon/icon.png

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#1A1A1A"
  image: assets/images/launchscreen/logo_light.png
  image_dark: assets/images/launchscreen/logo_dark.png
  branding: assets/images/launchscreen/branding_light.png
  branding_dark: assets/images/launchscreen/branding_dark.png

  android_12: 
    image: assets/images/launchscreen/logo_light.png
    image_dark: assets/images/launchscreen/logo_dark.png
    branding: assets/images/launchscreen/branding_light.png
    branding_dark: assets/images/launchscreen/branding_dark.png
    color: "#FFFFFF"
    color_dark: "#1A1A1A"
  android: true
  ios: false
  # dart run flutter_native_splash:create

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#228B22"
  adaptive_icon_foreground: "assets/images/icon/icon.png"
  # dart run flutter_launcher_icons
